[project]
name = "scrna"
version = "0.1.0"
description = "A Model Context Protocol server providing tools for scRNA analysis"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.0.0",
    "pydantic>=2.0.0",
]
